#+TITLE: Welcome to thermalSnap!
#+DATE: 2018-02-24
#+OPTIONS: toc:nil author:nil title:nil date:nil num:nil ^:{} \n:1 todo:nil
#+PROPERTY: header-args :exports both :eval no
#+LATEX_HEADER: \usepackage[margin=1.0in]{geometry}
#+LATEX_HEADER: \hypersetup{citecolor=black,colorlinks=true,urlcolor=blue,linkbordercolor=blue,pdfborderstyle={/S/U/W 1}}
#+LATEX_HEADER: \usepackage[round]{natbib}
#+LATEX_HEADER: \renewcommand{\bibsection}

* Motivation
This is the updated version of [[github.com/nkicg6/snakesnap][snakesnap]]. Snakesnap was first a simple command line script that controlled the Flir thermal camera in order to demonstrate what a snake would see using it's pit organs. It was developed as a quick demo for a Denver Science Museum project for kids by the Neuroscience program at University of Colorado Anschutz Medical Campus. Command line programs are easy to write but are virtually unusable if you are not familiar with programming languages. Since I wanted this project to be usable by everyone (and hopefully reused for other fun demos), I decided to make it into a GUI. My first attempt to write a GUI for snakesnap focused on the web browser via Flask, html, css, and javascript. This turned out to be fun but a lot more work than I anticipated-- especially since I wanted to interact with the file system and control GPIO pins-- something the browser is not designed for. 

+Thermalsnap uses the [[https://kivy.org/][Kivy]] GUI framework. I hope this will simplify both development (for me) and use (for you!).+
*Note* turns out that was not the simplest option...

*tkinter it is!*



* Installation
  This package is under development. Soon you will be able to =pip install thermalsnap= to use it. 

* More coming soon
